"""initial

Revision ID: 3abb1a0c1f17
Revises: 
Create Date: 2025-08-22 00:24:41.278604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3abb1a0c1f17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('limite_armazenamento_mb', sa.Integer(), nullable=True),
    sa.Column('recursos', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('plano_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plano_id'], ['planos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('arquivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('caminho', sa.String(length=500), nullable=False),
    sa.Column('tipo_mime', sa.String(length=120), nullable=True),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('arquivos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_arquivos_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('fotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('caminho', sa.String(length=500), nullable=False),
    sa.Column('legenda', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fotos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fotos_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('ideias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('prioridade', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ideias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ideias_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('pensamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pensamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pensamentos_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('transacoes_financeiras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transacoes_financeiras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transacoes_financeiras_categoria'), ['categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_transacoes_financeiras_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacoes_financeiras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transacoes_financeiras_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_transacoes_financeiras_categoria'))

    op.drop_table('transacoes_financeiras')
    with op.batch_alter_table('pensamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pensamentos_usuario_id'))

    op.drop_table('pensamentos')
    with op.batch_alter_table('ideias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ideias_usuario_id'))

    op.drop_table('ideias')
    with op.batch_alter_table('fotos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fotos_usuario_id'))

    op.drop_table('fotos')
    with op.batch_alter_table('arquivos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_arquivos_usuario_id'))

    op.drop_table('arquivos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    op.drop_table('planos')
    # ### end Alembic commands ###
