name: Deploy (Nexus)
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}
jobs:
  deploy:
    runs-on: [self-hosted, prod]
    steps:
      - name: Deploy via script local
        run: bash /home/widson/Projetos/Nexus/deploy/deploy.sh
